source "https://rubygems.org"

ruby "1.8.7"

gem "rails", "2.3.18"
gem "mysql"#, "2.8.1"

gem "rake"#, "0.8.7"
gem "solr-ruby"#, "0.0.8"
gem "json"#, "1.4.6"
gem "addressable"#, "2.2.2"
gem "daemons"#, "1.1.3"
gem "dnsruby"#, "1.53"
gem "SystemTimer"#, "1.2.3"
gem "libxml-ruby"#, "1.1.4"
gem "mongrel"#, "1.1.5"
gem "tzinfo"#, "0.3.31"

gem "rdoc"

# Frozen gems
gem "crack"#, "0.1.2", :path => "vendor/gems/crack-0.1.2"
gem "factory_girl"#, "1.2.3", :path => "vendor/gems/factory_girl-1.2.3"
gem "geokit", "1.3.2", :path => "vendor/gems/geokit-1.3.2"
gem "rpx_now", "0.5.10", :require => "rpx_now", :path => "vendor/gems/grosser-rpx_now-0.5.10"
gem "httparty", "0.4.3", :path => "vendor/gems/httparty-0.4.3"
gem "jnunemaker-twitter", "0.6.11", :require => "twitter", :path => "vendor/gems/jnunemaker-twitter-0.6.11"
gem "mash", "0.0.3", :path => "vendor/gems/mash-0.0.3"
gem "mocha", "0.9.8", :path => "vendor/gems/mocha-0.9.8"
gem "memcache-client", "1.7.4", :require => "memcache", :path => "vendor/gems/mperham-memcache-client-1.7.4"
gem "oauth", "0.3.6", :path => "vendor/gems/oauth-0.3.6"
gem "onyx-cache-money", "0.2.6.1", :require => "cache_money", :path => "vendor/gems/onyx-cache-money-0.2.6.1"
gem "rubaidh-google_analytics", "1.1.4", :require => "rubaidh/google_analytics", :path => "vendor/gems/rubaidh-google_analytics-1.1.4"
gem "ruby-hmac", "0.3.2", :require => "hmac", :path => "vendor/gems/ruby-hmac-0.3.2"
gem "seer", "0.6.1", :path => "vendor/gems/seer-0.6.1"
gem "soap4r", "1.5.8", :path => "vendor/gems/soap4r-1.5.8"
gem "version_info", "0.7.1", :path => "vendor/gems/version_info-0.7.1"
